name: "publish"
on:
  push:
    branches:
      - master

jobs:
  publish-tauri:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-10.15, ubuntu-latest, windows-latest] #macos-latest

    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v2
    - name: setup node
      uses: actions/setup-node@v1
      with:
        node-version: 16

    - name: install Rust stable
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    - name: install webkit2gtk (ubuntu only)
      if: matrix.platform == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y webkit2gtk-4.0

    - name: yarn install
      run: yarn


    - uses: Swatinem/rust-cache@v1
      with:
        working-directory: ./src-tauri

    # - name: cache tauri target
    #   uses: actions/cache@v2
    #   env:
    #     cache-name: cache-tauri-target
    #   with:
    #     path: |
    #       ./src-tauri/target
    #       ~/.cargo/registry/index
    #       ~/.cargo/registry/cache
    #       ~/.cargo/git
    #     key: ${{ runner.os }}-build-${{ env.cache-name }}
    #     restore-keys: |
    #       ${{ runner.os }}-build-${{ env.cache-name }}-
    #       ${{ runner.os }}-build-
    #       ${{ runner.os }}-

    # - name: build app
    #   run: yarn tauri build

    - uses: tauri-apps/tauri-action@v0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tagName: app-v__VERSION__ # the action automatically replaces \_\_VERSION\_\_ with the app version
        releaseName: "App v__VERSION__"
        releaseBody: "See the assets to download this version and install."
        releaseDraft: true
        prerelease: false